# RedisBungee configuration file.
# PLEASE READ THE WIKI: http://minecraft.imaginarycode.com/

# Redis server configuration. Learn more at http://redis.io.
redis-server: 127.0.0.1
redis-port: 6379

# If your Redis server requires a password, set it here.
redis-password: ""

# An identifier for this BungeeCord instance.
server-id: iluvbungee

# Whether or not RedisBungee should install its version of regular BungeeCord commands.
# Often, the RedisBungee commands are desired, but in some cases someone may wish to
# override the commands using another plugin.
#
# If you are just denying access to the commands, RedisBungee uses the default BungeeCord
# permissions - just deny them and access will be denied.
#
# Please note that with build 787+, most commands overridden by RedisBungee were moved to
# modules, and these must be disabled or overridden yourself.
register-bungee-commands: true

# Whether or not /glist showall output should match vanilla BungeeCord.
canonical-glist: true